### ISSUE TITLE
The example of HoC has problem?

### ISSUE THREAD

**Issue by anjianshi** [jurassix/react-immutable-render-mixin#11]
```js
import React from 'react';
import { immutableRenderDecorator } from 'react-immutable-render-mixin';

class Test extends React.Component {
  render() {
    return <div></div>;
  }
}

export default immutableRenderDecorator(Test);
```

The function `immutableRenderDecorator` doesn't return anything, so this will got a `cannot find module` error.

**Comment by jurassix** [comment]
@anjianshi lol! I'll get this resolved and published to npm soon. Stand by...

**Comment by jurassix** [comment]
@anjianshi This has been fixed in v0.9.1

If you have time please submit a PR with some tests. I've upgraded this library, which included adding basic testing infra. I'm planning on building out the test suite for this before a v1.0.0 release. Any help would be appreciated.

**Comment by jurassix** [comment]
@anjianshi please use v0.9.2

**Comment by anjianshi** [comment]
OK, thanks!
