### ISSUE TITLE
Support for functional components

### ISSUE THREAD

**Issue by zerkms** [jurassix/react-immutable-render-mixin#13]
Any plans for adding a support for the functional components for `immutableRenderDecorator`?

```js
import logo from './logo.png';

const Logo = () => <img src={logo} />;
export default immutableRenderDecorator(Logo);
```

**Comment by jurassix** [comment]
Sure, it would pretty easy to wrap the functional component in a __React.Component__ inside the decorator. Should be an easy PR if your interested? Otherwise, I'll try to knock it out soon.

**Comment by zerkms** [comment]
I am, just give me couple of evenings.

**Comment by jurassix** [comment]
Perfect. Thx!
