### ISSUE TITLE
Clarifications on the warning

### ISSUE THREAD

**Issue by Strato** [jurassix/react-immutable-render-mixin#23]
Hello,

Couple of weeks ago I was going to use this library when I saw your warning.

Can you explain this line?

> This library was created from experimentations with Immutable that were ultimately erroneous; improper usage of Immutable.js 💩.

Also there is something else that you could clarify for me.

Right now I often have `shouldComponentUpdate()` that looks like this:

```
private shouldComponentUpdate(newProps, newState) {
        const propsChanged = !Immutable.is(this.props.referentiel, newProps.referentiel)
            || this.props.multipleMode !== newProps.multipleMode
            || this.props.groupIsVisible !== newProps.groupIsVisible
            || this.props.searchButtonLabel !== newProps.searchButtonLabel
            || this.props.searchButtonClassName !== newProps.searchButtonClassName
            || this.props.forceSearchButtonDisabled !== newProps.forceSearchButtonDisabled
            || this.props.isFetchingForDisplay !== newProps.isFetchingForDisplay
            || this.props.isFetchingForSearch !== newProps.isFetchingForSearch
            || this.props.defaultSelection !== newProps.defaultSelection
            || this.props.onChange !== newProps.onChange
            || this.props.onSearchSubmit !== newProps.onSearchSubmit;

        const stateChanged = !Immutable.is(this.state.phaseRefIds, newState.phaseRefIds)
            || !Immutable.is(this.state.groupIds, newState.groupIds)
            || !Immutable.is(this.state.phaseIds, newState.phaseIds)
            || !Immutable.is(this.state.updperIds, newState.updperIds);

        return propsChanged || stateChanged;
    }
```

Of course it's tedious, which is why I wanted to use your library. But you say we should use PureRenderMixin.

Question is: are we not supposed to use `Immutable.is()` for props using Immutable types? As far as I know PureRenderMixin knows nothing about it. Or maybe it doesn't matter because Immutable makes sure pointers don't change if data doesn't, so a plain triple equals comparison is enough?

To make things clear: is it OK to use PureRenderMixin even with Immutable props?

**Comment by Strato** [comment]
OK. I found all the answers to my questions [here](https://github.com/jurassix/react-immutable-render-mixin/issues/19#issuecomment-222567064).

You should add a link to that issue in the warning on the front page.

**Comment by jurassix** [comment]
@Strato Thx for the suggestion. I'll work on adding more context and best practices to the README.
