### ISSUE TITLE
When doesn't the === work?

### ISSUE THREAD

**Issue by prakhar1989** [jurassix/react-immutable-render-mixin#6]
Hi Clint, first off let me thank you for open-sourcing this useful library! 

I'm fairly new to React (Immutable specifically) and I was having trouble wrapping my head around using Immutable to improve my app performance. Specifically, what I'm not understanding is in what cases does the `===` equality holds and in what cases would `Immutable.is` is required. 

From the [docs](https://facebook.github.io/react/docs/advanced-performance.html#immutable-js-to-the-rescue)
> So, Immutable data structures provides you a cheap and less verbose way to track changes on objects, which is all we need to implement shouldComponentUpdate. Therefore, if we model props and state attributes using the abstractions provided by immutable-js we'll be able to use PureRenderMixin and get a nice boost in perf.

However, in my tests I've found this to be not quite true (as a result of which I found this repo).

```javascript
var Block = Immutable.Record({
    id: 0,
    questions: Immutable.List(),
    subblocks: Immutable.List(),
    randomizable: true,
    ordering: false
});

var b1 = Block({id: 1});
var b2 = b1.set('randomizable', false);
var b3 = b2.set('randomizable', true);

console.log("b1 and b2:", b1 === b2);   // returns false
console.log("b1 and b3:", b1 === b3);   // also returns false

console.log("b1 and b2:", Immutable.is(b1, b2));  // returns false
console.log("b1 and b3:", Immutable.is(b1, b3));  // returns true
```

As seen above, it seems that the `PureRenderMixin` cannot be used, right? Is that the motivation behind this library? Also, if that is indeed the case, why do the React docs say so?

Thank you for your time!

**Comment by jurassix** [comment]
Hi Prakhar!

This is exactly the motivation for this library; I couldn't get Immutable referential equality to work with the `PureRenderMixin`.  I spoke with Lee (author of Immutable) at the React Conference in January, he said he is able to use `PureRenderMixin` within his apps. I haven't followed up with him for examples, so if you do please let me know.

I think it makes sense that the `PureRenderMixin` should work. I think if you updated your tests to compare the referential integrity of the Record properties (use `.get()`) then you will see more predictable results.

Good luck!

**Comment by prakhar1989** [comment]
Thanks Clint! However, since `shouldComponentUpdate` is called quite often aren't you worried that `Immutable.is` might turn out to be costly (ideally I should have numbers to back this up).

From the docs - 
> Basically, we ended up doing a deep comparison to make sure we properly track changes. In terms of performance, this approach is pretty expensive. It doesn't scale as we would have to write different deep equality code for each model

**Comment by jurassix** [comment]
Yes, I do think there is a performance penalty using `Immutable.is()`. I've run performance tests using React Immutable data with this library, and see about a 20% performance gain over React with non-Immutable data structures.

I think the trade off is when you must have an Immutable object and need to have referential integrity, then use this mixin for that component. But if you can modify your Component to take simple properties, coming from an Immutable object, then `PureRenderMixin` should work. 

Checkout this for more info on the performance gains https://github.com/jurassix/react-examples/tree/master/advanced/presentation

**Comment by prakhar1989** [comment]
> see about a 20% performance gain over React with non-Immutable data structures.
This is awesome! Just to clarify this was with immutable collections with `PureRenderMixin` or was it with this library?

Also, really appreciate sharing the PPT. Quite helpful! I have a quick question regarding the last slides - in the benchmarks that you carried out which configuration came out on top? Was it multiple react components with Immutability (Table) or TableRow? 

Thanks!

**Comment by jurassix** [comment]
The performance gains were with Immutable Collections and _this_ library. 

You can run or examine the code here: https://github.com/jurassix/react-examples/tree/master/advanced/table-multiple-immutable-components

The fastest (20% gains) was with multiple React Components, _this_ library, and Immutable data.

**Comment by prakhar1989** [comment]
Thank you very much for these clarifications, Clint! Really appreciate your help :grinning:
